sudo: required
language: node_js
node_js: 
- node
services:
- docker
cache:
    directories:
    - "$HOME/google-cloud-sdk/"
env:
    global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - PATH=$PATH:$HOME/google-cloud-sdk/bin
    - PROJECT_ID="uhlu-179602"
    - ZONE="us-central1-b"
    - IMAGE_NAME=uhlu:latest
    - FULL_IMAGE_NAME=gcr.io/$PROJECT_ID/$IMAGE_NAME
    - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/client-secret.json"
    - CLUSTER_NAME=uhlu
before_install:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud --quiet components update kubectl
- gcloud auth activate-service-account --key-file "${GOOGLE_APPLICATION_CREDENTIALS}";
- gcloud config set project $PROJECT_ID;
- gcloud config set compute/zone $ZONE;
install: true
before_script:
- docker build --no-cache=true -t $FULL_IMAGE_NAME .
- gcloud docker -- push $FULL_IMAGE_NAME
script:
- gcloud container clusters get-credentials $CLUSTER_NAME
- kubectl apply -f deployment.yml
- kubectl apply -f service.yml
- kubectl apply -f ingress.yml