'use strict';
module.exports = function(sequelize, DataTypes) {
        var Scout = sequelize.define('Scout', {
        	cum: { type: DataTypes.STRING,  defaultValue: "" },
        	foto: DataTypes.TEXT,
        	nombre: { type: DataTypes.STRING, defaultValue: "" },
        	genero: { type: DataTypes.STRING, defaultValue: "" },
        	fechanacimiento: DataTypes.DATE,
        	escuela: { type: DataTypes.STRING, defaultValue: "" },
        	email: { type: DataTypes.STRING, defaultValue: "" },
        	telefono: { type: DataTypes.STRING, defaultValue: "" },
        	domicilio: { type: DataTypes.STRING, defaultValue: "" },
        	porcentaje: { type: DataTypes.STRING, defaultValue: "" },
        	contacto1: { type: DataTypes.STRING, defaultValue: "" },
            parentezco1: { type: DataTypes.STRING, defaultValue: "" },
            contacto2: { type: DataTypes.STRING, defaultValue: "" },
            parentezco2: { type: DataTypes.STRING, defaultValue: "" },
            telefono1: { type: DataTypes.STRING, defaultValue: "" },
            telefono2: { type: DataTypes.STRING, defaultValue: "" },
            emailcontacto: { type: DataTypes.STRING, defaultValue: "" },
            tiposangre: { type: DataTypes.STRING, defaultValue: "" },
            peso: { type: DataTypes.STRING, defaultValue: "" },
            estatura: { type: DataTypes.STRING, defaultValue: "" },
            noafiliacion: { type: DataTypes.STRING, defaultValue: "" },
            seguro: { type: DataTypes.STRING, defaultValue: "" },
            especifique: { type: DataTypes.STRING, defaultValue: "" },
            pieplano: { type: DataTypes.INTEGER, defaultValue: 0 },
            zapato: { type: DataTypes.INTEGER, defaultValue: 0 },
            operacion: { type: DataTypes.INTEGER, defaultValue: 0 },
            limitacion: { type: DataTypes.INTEGER, defaultValue: 0 },
            transfusion: { type: DataTypes.INTEGER, defaultValue: 0 },
            alergia: { type: DataTypes.INTEGER, defaultValue: 0 },
            enfermedad: { type: DataTypes.INTEGER, defaultValue: 0 },
            tratamiento: { type: DataTypes.INTEGER, defaultValue: 0 },
            veroir: { type: DataTypes.INTEGER, defaultValue: 0 },
            aparato: { type: DataTypes.INTEGER, defaultValue: 0 },
            dieta: { type: DataTypes.INTEGER, defaultValue: 0 },
            drogas: { type: DataTypes.INTEGER, defaultValue: 0 },
            vacunas: { type: DataTypes.INTEGER, defaultValue: 0 },
            embarazo: { type: DataTypes.INTEGER, defaultValue: 0 },
            espoperacion: { type: DataTypes.STRING, defaultValue: "" },
            esplimitacion: { type: DataTypes.STRING, defaultValue: "" },
            esptransfusion: { type: DataTypes.STRING, defaultValue: "" },
            espalergia: { type: DataTypes.STRING, defaultValue: "" },
            espenfermedad: { type: DataTypes.STRING, defaultValue: "" },
            esptratamiento: { type: DataTypes.STRING, defaultValue: "" },
            espveroir: { type: DataTypes.STRING, defaultValue: "" },
            espaparato: { type: DataTypes.STRING, defaultValue: "" },
            espdieta: { type: DataTypes.STRING, defaultValue: "" },
            espdrogas: { type: DataTypes.STRING, defaultValue: "" },
            promesa: { type: DataTypes.INTEGER, defaultValue: 0 },
            etapa: { type: DataTypes.INTEGER, defaultValue: 0 },
            deporte: { type: DataTypes.INTEGER, defaultValue: 0 },
            ecologia: { type: DataTypes.INTEGER, defaultValue: 0 },
            expresion: { type: DataTypes.INTEGER, defaultValue: 0 },
            humanidades: { type: DataTypes.INTEGER, defaultValue: 0 },
            rescate: { type: DataTypes.INTEGER, defaultValue: 0 },
            ciencia: { type: DataTypes.INTEGER, defaultValue: 0 },
            vida: { type: DataTypes.INTEGER, defaultValue: 0 },
            desarrollo: { type: DataTypes.INTEGER, defaultValue: 0 },
            enlace: { type: DataTypes.INTEGER, defaultValue: 0 },
            fechapromesa: DataTypes.DATE,
            fechaetapa1: DataTypes.DATE,
            fechaetapa2: DataTypes.DATE,
            fechaetapa3: DataTypes.DATE,
            fechaetapa4: DataTypes.DATE,
            fechadeporte1: DataTypes.DATE,
            fechadeporte2: DataTypes.DATE,
            fechadeporte3: DataTypes.DATE,
            fechadeporte4: DataTypes.DATE,
            fechaecologia1: DataTypes.DATE,
            fechaecologia2: DataTypes.DATE,
            fechaecologia3: DataTypes.DATE,
            fechaecologia4: DataTypes.DATE,
            fechaexpresion1: DataTypes.DATE,
            fechaexpresion2: DataTypes.DATE,
            fechaexpresion3: DataTypes.DATE,
            fechaexpresion4: DataTypes.DATE,
            fechahumanidades1: DataTypes.DATE,
            fechahumanidades2: DataTypes.DATE,
            fechahumanidades3: DataTypes.DATE,
            fechahumanidades4: DataTypes.DATE,
            fecharescate1: DataTypes.DATE,
            fecharescate2: DataTypes.DATE,
            fecharescate3: DataTypes.DATE,
            fecharescate4: DataTypes.DATE,
            fechaciencia1: DataTypes.DATE,
            fechaciencia2: DataTypes.DATE,
            fechaciencia3: DataTypes.DATE,
            fechaciencia4: DataTypes.DATE,
            fechavida1: DataTypes.DATE,
            fechavida2: DataTypes.DATE,
            fechavida3: DataTypes.DATE,
            fechavida4: DataTypes.DATE,
            fechadesarrollo1: DataTypes.DATE,
            fechadesarrollo2: DataTypes.DATE,
            fechadesarrollo3: DataTypes.DATE,
            fechaenlace: DataTypes.DATE
	}, {
		//set the timestamps to be underscored: (created_at, updated_at)
		underscored: true,
		classMethods: {
			associate: function(models) {
                Scout.belongsTo(models.Patrulla)
			}
		}
	});
	return Scout;
};
